// flow-typed signature: b57d83c2ab92a84bd21528fc57a6b6e0
// flow-typed version: <<STUB>>/pug-lint_v^2.4.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug-lint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug-lint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug-lint/generators/rule-templates/rule' {
  declare module.exports: any;
}

declare module 'pug-lint/generators/rule-templates/test' {
  declare module.exports: any;
}

declare module 'pug-lint/generators/rule' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/cli' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/config-file' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/errors' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/linter' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/pug-file' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/reporters/console' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/reporters/inline' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-attribute-concatenation' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-attribute-interpolation' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-attribute-template-string' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-block-expansion' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-class-attribute-with-static-value' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-class-literals-before-attributes' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-class-literals-before-id-literals' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-class-literals' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-duplicate-attributes' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-html-text' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-id-attribute-with-static-value' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-id-literals-before-attributes' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-id-literals' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-legacy-mixin-call' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-multiple-line-breaks' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-space-after-code-operator' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-spaces-inside-attribute-brackets' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-specific-attributes' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-specific-tags' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-string-concatenation' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-string-interpolation' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-tag-interpolation' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/disallow-template-string' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/maximum-number-of-lines' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/require-class-literals-before-attributes' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/require-class-literals-before-id-literals' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/require-id-literals-before-attributes' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/require-line-feed-at-file-end' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/require-lower-case-attributes' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/require-lower-case-tags' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/require-space-after-code-operator' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/require-spaces-inside-attribute-brackets' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/require-specific-attributes' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/require-strict-equality-operators' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/validate-attribute-quote-marks' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/validate-attribute-separator' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/validate-div-tags' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/validate-extensions' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/validate-indentation' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/validate-line-breaks' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/validate-self-closing-tags' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/rules/validate-template-string' {
  declare module.exports: any;
}

declare module 'pug-lint/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug-lint/generators/rule-templates/rule.js' {
  declare module.exports: $Exports<'pug-lint/generators/rule-templates/rule'>;
}
declare module 'pug-lint/generators/rule-templates/test.js' {
  declare module.exports: $Exports<'pug-lint/generators/rule-templates/test'>;
}
declare module 'pug-lint/generators/rule.js' {
  declare module.exports: $Exports<'pug-lint/generators/rule'>;
}
declare module 'pug-lint/lib/cli.js' {
  declare module.exports: $Exports<'pug-lint/lib/cli'>;
}
declare module 'pug-lint/lib/config-file.js' {
  declare module.exports: $Exports<'pug-lint/lib/config-file'>;
}
declare module 'pug-lint/lib/errors.js' {
  declare module.exports: $Exports<'pug-lint/lib/errors'>;
}
declare module 'pug-lint/lib/linter.js' {
  declare module.exports: $Exports<'pug-lint/lib/linter'>;
}
declare module 'pug-lint/lib/pug-file.js' {
  declare module.exports: $Exports<'pug-lint/lib/pug-file'>;
}
declare module 'pug-lint/lib/reporters/console.js' {
  declare module.exports: $Exports<'pug-lint/lib/reporters/console'>;
}
declare module 'pug-lint/lib/reporters/inline.js' {
  declare module.exports: $Exports<'pug-lint/lib/reporters/inline'>;
}
declare module 'pug-lint/lib/rules/disallow-attribute-concatenation.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-attribute-concatenation'>;
}
declare module 'pug-lint/lib/rules/disallow-attribute-interpolation.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-attribute-interpolation'>;
}
declare module 'pug-lint/lib/rules/disallow-attribute-template-string.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-attribute-template-string'>;
}
declare module 'pug-lint/lib/rules/disallow-block-expansion.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-block-expansion'>;
}
declare module 'pug-lint/lib/rules/disallow-class-attribute-with-static-value.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-class-attribute-with-static-value'>;
}
declare module 'pug-lint/lib/rules/disallow-class-literals-before-attributes.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-class-literals-before-attributes'>;
}
declare module 'pug-lint/lib/rules/disallow-class-literals-before-id-literals.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-class-literals-before-id-literals'>;
}
declare module 'pug-lint/lib/rules/disallow-class-literals.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-class-literals'>;
}
declare module 'pug-lint/lib/rules/disallow-duplicate-attributes.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-duplicate-attributes'>;
}
declare module 'pug-lint/lib/rules/disallow-html-text.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-html-text'>;
}
declare module 'pug-lint/lib/rules/disallow-id-attribute-with-static-value.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-id-attribute-with-static-value'>;
}
declare module 'pug-lint/lib/rules/disallow-id-literals-before-attributes.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-id-literals-before-attributes'>;
}
declare module 'pug-lint/lib/rules/disallow-id-literals.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-id-literals'>;
}
declare module 'pug-lint/lib/rules/disallow-legacy-mixin-call.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-legacy-mixin-call'>;
}
declare module 'pug-lint/lib/rules/disallow-multiple-line-breaks.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-multiple-line-breaks'>;
}
declare module 'pug-lint/lib/rules/disallow-space-after-code-operator.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-space-after-code-operator'>;
}
declare module 'pug-lint/lib/rules/disallow-spaces-inside-attribute-brackets.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-spaces-inside-attribute-brackets'>;
}
declare module 'pug-lint/lib/rules/disallow-specific-attributes.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-specific-attributes'>;
}
declare module 'pug-lint/lib/rules/disallow-specific-tags.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-specific-tags'>;
}
declare module 'pug-lint/lib/rules/disallow-string-concatenation.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-string-concatenation'>;
}
declare module 'pug-lint/lib/rules/disallow-string-interpolation.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-string-interpolation'>;
}
declare module 'pug-lint/lib/rules/disallow-tag-interpolation.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-tag-interpolation'>;
}
declare module 'pug-lint/lib/rules/disallow-template-string.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/disallow-template-string'>;
}
declare module 'pug-lint/lib/rules/maximum-number-of-lines.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/maximum-number-of-lines'>;
}
declare module 'pug-lint/lib/rules/require-class-literals-before-attributes.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/require-class-literals-before-attributes'>;
}
declare module 'pug-lint/lib/rules/require-class-literals-before-id-literals.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/require-class-literals-before-id-literals'>;
}
declare module 'pug-lint/lib/rules/require-id-literals-before-attributes.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/require-id-literals-before-attributes'>;
}
declare module 'pug-lint/lib/rules/require-line-feed-at-file-end.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/require-line-feed-at-file-end'>;
}
declare module 'pug-lint/lib/rules/require-lower-case-attributes.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/require-lower-case-attributes'>;
}
declare module 'pug-lint/lib/rules/require-lower-case-tags.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/require-lower-case-tags'>;
}
declare module 'pug-lint/lib/rules/require-space-after-code-operator.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/require-space-after-code-operator'>;
}
declare module 'pug-lint/lib/rules/require-spaces-inside-attribute-brackets.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/require-spaces-inside-attribute-brackets'>;
}
declare module 'pug-lint/lib/rules/require-specific-attributes.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/require-specific-attributes'>;
}
declare module 'pug-lint/lib/rules/require-strict-equality-operators.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/require-strict-equality-operators'>;
}
declare module 'pug-lint/lib/rules/validate-attribute-quote-marks.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/validate-attribute-quote-marks'>;
}
declare module 'pug-lint/lib/rules/validate-attribute-separator.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/validate-attribute-separator'>;
}
declare module 'pug-lint/lib/rules/validate-div-tags.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/validate-div-tags'>;
}
declare module 'pug-lint/lib/rules/validate-extensions.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/validate-extensions'>;
}
declare module 'pug-lint/lib/rules/validate-indentation.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/validate-indentation'>;
}
declare module 'pug-lint/lib/rules/validate-line-breaks.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/validate-line-breaks'>;
}
declare module 'pug-lint/lib/rules/validate-self-closing-tags.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/validate-self-closing-tags'>;
}
declare module 'pug-lint/lib/rules/validate-template-string.js' {
  declare module.exports: $Exports<'pug-lint/lib/rules/validate-template-string'>;
}
declare module 'pug-lint/lib/utils.js' {
  declare module.exports: $Exports<'pug-lint/lib/utils'>;
}
