// flow-typed signature: 7e0b8e345bbb9b9aebf3f159e64c49b5
// flow-typed version: <<STUB>>/vuex-router-sync_v^4.1.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuex-router-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuex-router-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'vuex-router-sync/index' {
  declare module.exports: $Exports<'vuex-router-sync'>;
}
declare module 'vuex-router-sync/index.js' {
  declare module.exports: $Exports<'vuex-router-sync'>;
}
